### ISSUE TITLE
'go get' fails

### ISSUE THREAD

**Issue by vulcanfan** [evanphx/json-patch#102]
Hi, 
Tried the 'go get' in the README but I just the response as below:
```
# go get -u gopkg.in/evanphx/json-patch.v4
go: gopkg.in/evanphx/json-patch.v4@v4.7.0: go.mod has non-....v4 module path "github.com/evanphx/json-patch" at revision v4.7.0
```
Getting v5 gives a similar error.
What am I doing wrong?
Many thanks

**Comment by palourde** [comment]
@vulcanfan I believe you could do `go get github.com/evanphx/json-patch/v5` and import it as `jsonpatch "github.com/evanphx/json-patch/v5"`.

**Comment by evanphx** [comment]
Yes, we should probably update the README to indicate using the directory for the proper version now.

**Comment by evanphx** [comment]
Ok, fixed the README.
