### ISSUE TITLE
Remove may cause invalid index error

### ISSUE THREAD

**Issue by cwdsuzhou** [evanphx/json-patch#106]
Test code as follow
```
package main

import (
	"fmt"

	jsonpatch "github.com/evanphx/json-patch"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/serializer"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
)

var scheme = runtime.NewScheme()
var codecs = serializer.NewCodecFactory(scheme)

func init() {
	addToScheme(scheme)
}

func addToScheme(scheme *runtime.Scheme) {
	utilruntime.Must(corev1.AddToScheme(scheme))
}

func main() {
	podStr := `
{
  "spec": {
    "tolerations": [
      {
        "key": "role",
        "operator": "Equal",
        "value": "test",
        "effect": "NoSchedule"
      },
      {
        "key": "node.kubernetes.ionot-ready",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": 300
      },
      {
        "key": "node.kubernetes.io/unreachable",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": 300
      }
    ]
  }
}
`
	pod := corev1.Pod{}
	deserializer := codecs.UniversalDeserializer()
	if _, _, err := deserializer.Decode([]byte(podStr), nil, &pod); err != nil {
		fmt.Println(err)
		return
	}
	p := `[{"op":"remove","path":"/spec/tolerations/1"},{"op":"remove","path":"/spec/tolerations/2"}]`
	Patch, err := jsonpatch.DecodePatch([]byte(p))
	if err != nil {
		fmt.Println(err)
		return
	}
	bytes, err := Patch.Apply([]byte(podStr))
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(string(bytes))
}
```

this error happen occur
```
Unable to access invalid index: 2
```

**Comment by evanphx** [comment]
As I mentioned in #107 I think your code is assuming incorrectly. You should delete /1 and then /1 again or reverse the order.

**Comment by maeglindeveloper** [comment]
Hi everyone, 
I'm facing the exact same error.
any news on this ?

@evanphx reading you, it means that we should not have 2 remove operations on the same slice, otherwise it would fail every time ? That is a strange behaviour ? It is often that multiple items in an array would be removed ?

Looking forward to hear / have a solution on this :) 
Thanks in advance

**Comment by maeglindeveloper** [comment]
In addition to my previous comment, here is an example that shows the issue.
https://play.golang.org/p/GCvZDepLm32

**Comment by evanphx** [comment]
@maeglindeveloper when item 1 is removed, it doesn't leave a blank there, so item 2 becomes item 1. That is part of the spec. So if you want to delete them both, either delete `/1` and then `/1` again, or delete `/2` and then `/1`.

**Comment by maeglindeveloper** [comment]
Whoa ... ok, that is a quick answer and a fast closed talk ... 
thanks anyway for your time & work. I will try to find a solution to better handle this on my own.

**Comment by cwdsuzhou** [comment]
@maeglindeveloper PR  merged, seems  this issue  has been fixed now!
