### ISSUE TITLE
Introduce AllowMissingPathOnRemove

### ISSUE THREAD

**Issue by vassilvk** [evanphx/json-patch#115]
This is a proposal for a new package-level flag `AllowMissingPathOnRemove`.
When this flag is set to `true`, JSON-Patch `remove` operations do not fail when the target `path` is missing from the container being patched.
The value of `AllowMissingPathOnRemove` defaults to `false` to maintain backward compatibility with previous functionality.

## Reasoning
The current implementation fails the entire patch when a remove operation includes a missing path.
There are use cases where the user just needs an item gone from the final document. If it's already missing from the document, that's ok - don't fail.
An alternative remove-if-it-exists solution based on error handling against the current implementation does not work for multi-operation patches, because if one `remove` operation fails, the entire patch is failed.

**Comment by vassilvk** [comment]
@evanphx - I will be submitting a PR for this issue soon.

**Comment by evanphx** [comment]
I'd rather not continue to add these toplevel options. I think the right solution is, instead, to accumulate errors found trying to apply the patch and then return them all at once. That would allow you the ability to inspect the errors and disregard the error if they were all for removing a non-existentant path.

**Comment by vassilvk** [comment]
Just to make sure I understand, are you suggesting to change the signature of `func (p Patch) Apply(doc []byte) ([]byte, error)` to `func (p Patch) Apply(doc []byte) ([]byte, []error)`?

Won’t this break existing clients?

Or are you thinking a new method?

Also, in order for this to work, it sounds like the method will be returning both a patched document and a slice of errors, so in case of errors will it just ignore the errored operations and just keep going, effectively returning a partially patched document? How will the user inspect the errors? By error type? Will this require the introduction of a new error type/types to capture the type of the offending operation?

In addition, how will hard errors such as the ones returned by ` json.Unmarshal`, `json.Marshal` and `json.MarshalIndent` fit in this new approach?

**Comment by evanphx** [comment]
No, `Apply` would still return `([]byte, error)` but within `Apply`, we'd accumulate the errors and then return, say, a `PatchError` type that contains all the accumulated errors.

I think that the non-patch related errors like the ones returned from `json.Marshal` would be "hard" errors, returning immediately.

**Comment by vassilvk** [comment]
My only concern is that changing the type of the error returned by Apply might still break existing clients who are already inspecting the type/contents of the error.

**Comment by evanphx** [comment]
We'd be changing the concrete type only, the exposed type would still be `error`. No one is dependent on the concrete type returned now I doubt. And even if they are, I'm ok breaking that contract.

**Comment by evanphx** [comment]
I'd be open to `ApplyWithOptions`, I think that's ok.

**Comment by vassilvk** [comment]
I’ll put together a PR.

**Comment by vassilvk** [comment]
Closed in favor of #117.
