### ISSUE TITLE
Ordering of object keys is not preserved

### ISSUE THREAD

**Issue by jamesphillpotts-fr** [evanphx/json-patch#128]
As per https://github.com/golang/go/issues/27179, sometimes the changes in some JSON content need to be read and compared by humans, and if the content is reordered by the applying of a JSON patch this is made hard to do.

This library should make the changes specified by patches in a non-destructive way to the existing content to facilitate readability by human users.

**Comment by vtolstov** [comment]
did you mind to publish release after this change?

**Comment by evanphx** [comment]
It has been released, there are newer tags with this.
