### ISSUE TITLE
"null" values are dropped from arrays

### ISSUE THREAD

**Issue by pacoxu** [evanphx/json-patch#132]
Open an issue for https://github.com/kubernetes/kubernetes/issues/98080

Why JSON should remove all nulls in the array?
https://github.com/evanphx/json-patch/blob/master/merge.go#L76-L89

Is there a reason, or a bug?

**Comment by apelisse** [comment]
I'm not a lawyer :-), but here's how I read the [spec](https://tools.ietf.org/html/rfc7386):
- Section [1](https://tools.ietf.org/html/rfc7386#section-1), it's arguable whether this means that items in an array should be removed, especially since arrays are supposed to be strictly replaced.
> Null values in the merge patch are given special meaning to indicate the removal of existing values in the target.
- Section [2](https://tools.ietf.org/html/rfc7386#section-2), the example algorithm replaces lists altogether with no changes, as expected:
> ```python
> define MergePatch(Target, Patch):
>  if Patch is an Object:
>    if Target is not an Object:
>  Target = {} # Ignore the contents and set it to an empty Object
>    for each Name/Value pair in Patch:
>  if Value is null:
>    if Name exists in Target:
>      remove the Name/Value pair from Target
>  else:
>    Target[Name] = MergePatch(Target[Name], Value)
>    return Target
>  else:
>    return Patch
>```

**Comment by pacoxu** [comment]
I read the spec, examples from the spec like below.
ORIGINAL | PATCH | RESULT
-- | -- | --
{"a":"b"} | {"a":"c"} | {"a":"c"}
   {"a":"b"}   |   {"b":"c"}   |   {"a":"b",  "b":"c"}
   {"a":"b"}   |   {"a":null}   |   {}
   {"a":"b", "b":"c"} |       {"a":null}   |   {"b":"c"}
   {"a":["b"]}     |      {"a":"c"}   |   {"a":"c"}
   {"a":"c"}   |   {"a":["b"]}     |  {"a":["b"]}
   ["a","b"]   |    ["c","d"]   |    ["c","d"]
   {"a":"b"}   |    ["c"]       |    ["c"]
   {"a":"foo"}  |   null       |     null
   {"a":"foo"}   |  "bar"     |      "bar"
   {"e":null}   |     {"a":1}       |    {"e":null, "a":1}

Currently, we want to define examples for arrays with null values:

ORIGINAL | PATCH | Current RESULT | RESULT without pruneNullInArray 
-- | -- | -- | -- 
  ["a",null]   |     [null]     |    [] | [null]
  ["a"]   |     [null]     |    [] | [null]
  ["a", "b"]   |     ["a",null]     |    ["a"] |  ["a",null]
   {"a":["b"]}     |      {"a": ["b", null]}   |   {"a":["b"]}  | {"a":["b", null]} 
   {"a":[]}     |      {"a": ["b", null, null, "a"]}   |   {"a":["b", "a"]}  | {"a":["b", null,  null, "a"]}

**Comment by apelisse** [comment]
@pacoxu In case it's not clear, I think we agree. Lists should be replaced without editing, i.e. nulls should be preserved. And yes, the spec doesn't have a single example with a null in a list.

**Comment by pacoxu** [comment]
If this is arguable, an option for this would be necessary.

Let users decide which suits their scenarios.

**Comment by apelisse** [comment]
I don't think we should ever drop nulls in arrays.

**Comment by pacoxu** [comment]
@evanphx  would you release a new version? Thanks.

> We probably need to update the version of json-patch used in kubernetes now!
