### ISSUE TITLE
help or suggestions required

### ISSUE THREAD

**Issue by srinivasj-sys** [evanphx/json-patch#133]
{"op": "add", "path": "/application/application/pages/TestPage", "value": "{"name": "TestPage", "type": "application"}"}
invalid character 'n' after object key:value pair

If I give "value" : "{\\"name\\": \\"TestPage\\", \\"type\\": \\"application\\"}" the output of 
patch.apply(original, added) is

https://play.golang.org/p/6vqpy50kB0C

{
    "description": "This is description of the new solution",
    "id": "test_create_solution",
    "pages": {
       "Home": {
          "name": "Home",
          "type": "application"
       },
       "TestPage": "{\\"name\":\\"TestPage\\",\\"type\\":\\"application\\"}"
    }
 }

**Comment by evanphx** [comment]
That is invalid JSON, the patch needs to be valid JSON. You've quoted the { before name accidentally.

**Comment by srinivasj-sys** [comment]
apologies. I should've closed it myself. I had it figured out and working.

Thanks for looking into the issue and suggesting the correct fix.
