### ISSUE TITLE
Can we have the unexpected operation kind error in json patch be an exported error value pls

### ISSUE THREAD

**Issue by 2785** [evanphx/json-patch#136]
Use case: on a client I'd like to return a bad request error if the patch request has a invalid operation in it. I can do that now but it requires a `strings.HasPrefix` which is kind of sketch. 

Would be great if that error can join its sentinel error friends and be exported :wink:

**Comment by kszafran** [comment]
I'm not 100% sure I understood your idea, but I think I'd be interested in something similar. I'd like to return 400 or 422 from by API, depending on whether the JSON Patch itself is invalid (400) or it fails to apply (422). Currently I'm doing:
```go
func failedToApply(err error) bool {
	return errors.Is(err, jsonpatch.ErrTestFailed) || errors.Is(err, jsonpatch.ErrInvalidIndex) ||
		(errors.Is(err, jsonpatch.ErrMissing) &&
			(strings.Contains(err.Error(), "operation does not apply") ||
				strings.Contains(err.Error(), "nonexistent key")))
}
```
But I agree it's not pretty.

**Comment by evanphx** [comment]
We can and should make it easier to detect this issue, totally agree.

**Comment by 2785** [comment]
I actually can't remember what I was on about either. It seems like I was asking for the 
```go
	ErrTestFailed   = errors.New("test failed")
	ErrMissing      = errors.New("missing value")
	ErrUnknownType  = errors.New("unknown object type")
	ErrInvalid      = errors.New("invalid state detected")
	ErrInvalidIndex = errors.New("invalid index referenced")
```

exported errors, which already exist in a commit from 2 years ago. Odd :thinking:
