### ISSUE TITLE
upgrading 4.10.0 failed for semantic import versioning is required

### ISSUE THREAD

**Issue by pacoxu** [evanphx/json-patch#145]
go mod download github.com/evanphx/json-patch@v4.10.0

> go mod download: github.com/evanphx/json-patch@v4.10.0+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required

No go.mod file in https://github.com/evanphx/json-patch/tree/v4.9.0
But there is a go.mod in https://github.com/evanphx/json-patch/tree/v4.10.0

**Comment by liggitt** [comment]
correct... only the v5 subfolder can contain a go.mod file

**Comment by BenTheElder** [comment]
see previously: https://github.com/evanphx/json-patch/issues/98

**Comment by evanphx** [comment]
Ack, I added go.mod stuff back in January to sort out CI stuff accidentally. I'll sort this out now.

**Comment by evanphx** [comment]
Ok, I've cleaned it up and published 4.11.0.

**Comment by BenTheElder** [comment]
Thanks!

**Comment by pacoxu** [comment]
Thank you all.
