### ISSUE TITLE
panic instead of returning an error

### ISSUE THREAD

**Issue by alizx** [evanphx/json-patch#15]
most of the when pointing to non existing propertis and malformated the patch json cause a panic instead of returning an error.
here are some examples : 
this the doc before any patch
{
"creation_date":"2015-09-14T13:21:48.82+04:30",
"host_id":"55f68aa42bdf2711fe000001",
"identifier":"host1",
"key":"host",
"now_playing":null,
"owner":{
"uuid":"1dd60c63-1a49-492b-8298-980d6f1b8e9c",
"username":"ali",
"firstname":"",
"lasttname":""
},
"playlist":{
"playlist_id":"host1",
"songs":{
},
"date":"2015-09-14T13:21:48.82+04:30"
},
"users":[
]
}
these too patches cause panic:
 [ { "op": "replace", "path": "/key/2", "value": "host" }]
 [ { "op": "replace", "path": "//key", "value": "host" }]

**Comment by evanphx** [comment]
Fixed in PR. Thanks!
