### ISSUE TITLE
Option to keep ordering when using the CLI

### ISSUE THREAD

**Issue by balcsida** [evanphx/json-patch#150]
Hey folks,

Thanks for this amazing implementation of json-patch in Go! 🙇 
My question is related to #128: would it be possible to keep the ordering of the input file while using the CLI?

**Comment by JeffreyFalgout** [comment]
I'm pretty sure this was fixed in #128, but I do notice that this was only fixed in the v5/ version of the code (see #130).

@mrpotes @evanphx should this also be addressed in the not-v5/ version of the code? I guess maybe a higher level question: Why is there a separate v5/ directory?

**Comment by balcsida** [comment]
Sorry, I only tried with the CLI and it seems that it modified the order

**Comment by balcsida** [comment]
Ohh, I see, after installing the CLI with the following command, it worked as expected:
```
go install github.com/evanphx/json-patch/v5/cmd/json-patch@latest
```

This can be used as a workaround until #154 is merged.

Many-many thanks @JeffreyFalgout for tackling this down :bow:
