### ISSUE TITLE
Consider using json-iterator

### ISSUE THREAD

**Issue by vincepri** [evanphx/json-patch#151]
Hi @evanphx, would you be open to a PR that introduces both benchmarks for the main exposed functions and replaces `encoding/json` with a compatible `json-iterator/go` encoder/decoder?

Some additional context: we're using the `json-patch` library extensively in Cluster API https://github.com/kubernetes-sigs/cluster-api/blob/8ab546aa392cb5d82da33a76f1f860bdbc40e05b/controllers/topology/internal/mergepatch/mergepatch.go  and in Controller Runtime. Patches are applied multiple times in a row during a reconciliation of an object and seems jsoniter could allow us to save some CPU cycles during each reconciliation.

If you're open to it, we can prepare a PR that adds both benchmarks and the new code so we can show the immediate benefits, thoughts?

**Comment by sbueringer** [comment]
I would give it a try.

**Comment by vincepri** [comment]
Closing this for now, Kubernetes is moving away from json-iterator and the project seems a bit unmaintained
