### ISSUE TITLE
CreateMergePatch: Numbers may get truncated due to always being treated as float64

### ISSUE THREAD

**Issue by alvaroaleman** [evanphx/json-patch#189]
Hey there,

Thanks for creating this library! We are using it downstream in [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) and recently someone posted [an issue](https://github.com/kubernetes-sigs/controller-runtime/issues/2603) that some of their int64s get truncated when using [CreateMergePatch](https://github.com/kubernetes-sigs/controller-runtime/blob/2154ffbc22e26ffd8c3b713927f0df2fa40841f2/pkg/client/patch.go#L136). From what I can tell, this is caused by numbers always being treated as float64.

Is this something that is a) realistically possible to fix and b) something you would consider changing?

Thanks in advance!

**Comment by evanphx** [comment]
Hiya! I'll have a look.

**Comment by evanphx** [comment]
Turned out to be a fairly easy fix, just need to avoid using float64. Have a look at #194.

**Comment by alvaroaleman** [comment]
That did the trick, thank you so much for looking into it!
