### ISSUE TITLE
move fails with "missing value" if from is ""

### ISSUE THREAD

**Issue by lucastheisen** [evanphx/json-patch#192]
According to the [JSON Pointer RFC 6901](https://datatracker.ietf.org/doc/html/rfc6901#section-5):

> The following JSON strings evaluate to the accompanying values:
> 
>     ""           // the whole document

But using that as a `from` results in a `missing value` error.

Adding this test will demonstrate the bug:

```golang
func TestMoveFromRoot(t *testing.T) {
	expected := `{"baz":{"foo":"bar"}}`
	res, err := applyPatch(`{"foo":"bar"}`, `[{"op":"move","from":"","path":"/baz"}]`)
	if err != nil {
		t.Errorf("unexpected error: %+v", err)
	} else if res != expected {
		t.Errorf("expected:\n%s\ngot:\n%s", expected, res)
	}
}
```

**Comment by lucastheisen** [comment]
Well, i just saw this in the [RFC for JSON Patch](https://datatracker.ietf.org/doc/html/rfc6902#section-4.4):

>  The "from" location MUST NOT be a proper prefix of the "path"
>  location; i.e., a location cannot be moved into one of its children.

So my use case is _invalid_ (as is the test per-se)...  But the lack of support for `""` JSON Pointer may still be something you want to address.  You can close this issue out if you would like, or modify it to deal with the JSON Pointer support.

**Comment by evanphx** [comment]
@lucastheisen Gotcha gotcha. Trying some other json patch implementations, they largely fail to handle when `from` is `""`, so I think we're in a bit of uncharted waters here.

**Comment by evanphx** [comment]
Could you have a look at #193 and give me your thoughts? Thanks!

**Comment by lucastheisen** [comment]
@evanphx , that merge looks great.
