### ISSUE TITLE
`>` character is not decoded properly when applying json patches

### ISSUE THREAD

**Issue by nvelat** [evanphx/json-patch#198]
The `>` character is decoded as unicode rather than text after applying a json patch. Here's an example:

```
package main

import (
	"fmt"

	jsonpatch "github.com/evanphx/json-patch/v5"
)

func main() {
	original := []byte(`{
  "version": "0.1.0",
  "engines": {
    "node": ">= 10.16.3"
  }
}`)
	patchJSON := []byte(`[{"op": "replace", "path": "/version", "value": "0.2.0"}]`)
	patch, err := jsonpatch.DecodePatch(patchJSON)
	if err != nil {
		panic(err)
	}
	modified, err := patch.ApplyIndent(original, "  ")
	if err != nil {
		panic(err)
	}

	fmt.Printf("Original document:\n%s\n", original)
	fmt.Printf("Modified document:\n%s\n", modified)
}
```
Output:

```
Original document:
{
  "version": "0.1.0",
  "engines": {
    "node": ">= 10.16.3"
  }
}
Modified document:
{
  "version": "0.2.0",
  "engines": {
    "node": "\u003e= 10.16.3"
  }
}
```

**Comment by evanphx** [comment]
The reason for this is that encoding/json escapes for HTML inclusion by default. I'm not sure I want to change that at this stage of the game, it could subtle break anyone that uses the output directly.

**Comment by nvelat** [comment]
Hmm, is it possible to get a new `ApplyOption` that allows us to `SetEscapeHTML(false)` on the json encoder? That's how you would normally work around this in the `encoding/json` library

**Comment by evanphx** [comment]
5.9.0 includes a new `EscapeHTML` value on ApplyOptions you can set to control this behavior.
