### ISSUE TITLE
Regression in 5.8.0: cannot create `jsonpatch.Operation` object

### ISSUE THREAD

**Issue by ItalyPaleAle** [evanphx/json-patch#199]
We are using this code which works in 5.7.0:

```go
patchOp := jsonpatch.Operation{
	"op":   ptr.Of(json.RawMessage(`"` + op + `"`)),
	"path": ptr.Of(json.RawMessage(`"` + path + `"`)),
}
```

In 5.8.0, this fails to build because the `json` package used by the library internally is an internal package and we cannot import it.

**Comment by evanphx** [comment]
That should still work fine, you can use `encoding/json.RawMessage` and it would work fine.

**Comment by ItalyPaleAle** [comment]
It fails to build using `encoding.json`.

**Comment by ItalyPaleAle** [comment]
We are using `encoding/json` and it fails to build on 5.8.0: https://github.com/dapr/dapr/actions/runs/7547911615/job/20548872383

It works with 5.7.0

**Comment by evanphx** [comment]
Oh oh, I see. I'll have 5.8.1 out in a jiff with a fix.

**Comment by ItalyPaleAle** [comment]
Thank you for the very quick response :)

**Comment by evanphx** [comment]
Ok, 5.8.1 is out, please let me know if that fixes it for you!

**Comment by ItalyPaleAle** [comment]
Confirming that 5.8.1 fixed the issue, thank you!
