### ISSUE TITLE
When producing a merge patch, arrays within objects will always be considered different even if they're not

### ISSUE THREAD

**Issue by rengawm** [evanphx/json-patch#21]
Given this JSON object:
```
{
  "OuterArray": [
    {
      "InnerArray": [
        {
          "StringAttr": "abc123"
        }
      ],
      "StringAttr": "def456"
    }
  ]
}
```

If I pass that object as both the original and new object to CreateMergePatch, it will return a non-empty merge patch containing the whole object (although if there were additional top-level values which were identical and not arrays, they would be eliminated correctly)

This is due to lack of handling of arrays being within objects in `matchesValue`. PR #20 fixes this.

**Comment by evanphx** [comment]
Fixed in PR. Thanks!
