### ISSUE TITLE
Unescaping '~1' and '~0' in path?

### ISSUE THREAD

**Issue by 0x777** [evanphx/json-patch#23]
They are used to escape `/` and `~` respectively in the path ([ref](http://jsonpatch.com/)). Does the library handle this?

**Comment by jimmidyson** [comment]
I've been trying to use JSON patch with Kubernetes that uses this library to apply patches & am hitting this issue. Should be a pretty simple fix hopefully, will look if I get time.

**Comment by 0x777** [comment]
@jimmidyson That would be great. Even I've hit this issue when patching k8s resources.
