### ISSUE TITLE
RFC 6902 escaping in merge.go

### ISSUE THREAD

**Issue by asac** [evanphx/json-patch#37]
Hi, 

maybe I missed something, but isn't the patch.go about RFC6902 patches while merge.go is about RFC7xxx ?

If so, why do we escape "/" like in RFC 6092 in merge.go?

Thanks

**Comment by asac** [comment]
any insights?

**Comment by evanphx** [comment]
@asac Any tests for the change in your fork? I'm not sure what behavior you're looking that is wrong?
