### ISSUE TITLE
Use semver tags

### ISSUE THREAD

**Issue by rwestlund** [evanphx/json-patch#47]
I'd be nice to have semver tags (e.g. v1.0.0) so I can pin by version rather than hash.  And so that I know what to expect when I update.

**Comment by clagraff** [comment]
I would second this @evanphx ✔️ 

This would enable everyone to use tools like [gopgk](https://labix.org/gopkg.in) or [go dep](https://github.com/golang/dep) for managing json-patch as a dependency more easily, as they could then be able to specify specific versions they would like to use.

Plus, then there can be less worry about backword-breaking being merged in and affecting everyone, similar to what happened after the [PR #41](https://github.com/evanphx/json-patch/pull/41).

**Comment by evanphx** [comment]
I guess it doesn't hurt. I'll just bump it at random times then 😄

**Comment by evanphx** [comment]
I added master as 3.0.0
