### ISSUE TITLE
implement softfail

### ISSUE THREAD

**Issue by bechtoldt** [evanphx/json-patch#51]
I'm try to use json-patch to normalize json objects since the input json objects can be very different, e.g. some fields are set, some aren't.

When using op remove or replace json-patch fails and terminates because it failed to apply the patch. I'd like to ignore this kind of error (mapping with a specific key doesn't exist), so all other patches will be applied anyway.

**Comment by evanphx** [comment]
@bechtoldt You'd probably be best copying this code into your own repo and then editing it to match the semantics you neeed.
