### ISSUE TITLE
Applying Merge Patch

### ISSUE THREAD

**Issue by ernsheong** [evanphx/json-patch#54]
README talks about creating a merge patch, but does this library support applying the merge patch?

p.s. by merge patch I mean `{"height":null,"name":"Jane"}` and not `{"op": "replace", "path": "/name", "value": "Jane"}`.

**Comment by ernsheong** [comment]
It appears that `jsonpatch.MergePatch` does this but README fails to highlight it, so maybe README needs an update.

**Comment by clagraff** [comment]
Hi @ernsheong 
If you happen to have a minute, can you let me know if this pull request addresses your issue?
https://github.com/evanphx/json-patch/pull/55

I've updated a section to now provide a more an explicit example for creating and applying a merge patches to the readme.

**Comment by ernsheong** [comment]
@clagraff excellent! I would suggest to also edit the main description of the project:

Example:
- https://github.com/evanphx/json-patch/pull/55/files#diff-04c6e90faac2675aa89e2176d2eec7d8R3 (`... as well as generate *and apply* merge-patches`)
- https://github.com/evanphx/json-patch/pull/55/files#diff-04c6e90faac2675aa89e2176d2eec7d8R6 (`... as well as create *and apply*`

**Comment by clagraff** [comment]
Thanks for the suggestion. When I have a moment I will see about changing it in my pr 👍

**Comment by clagraff** [comment]
Hey @ernsheong, would something like the following be better for the project description?


> `jsonpatch` is a library which provides functionallity for both applying
[RFC6902 JSON patches](http://tools.ietf.org/html/rfc6902) against documents, as well as for calculating & applying
[RFC7396 JSON merge patches](https://tools.ietf.org/html/rfc7396).

**Comment by evanphx** [comment]
Merged #55 to deal with this!

**Comment by ernsheong** [comment]
Closing this!
