### ISSUE TITLE
Creating  RFC6902 Patch Documents

### ISSUE THREAD

**Issue by seddonm1** [evanphx/json-patch#56]
Hi,
Is there a plan to create the RFC6902 patches as well as applying them? There are a few libraries floating around and this looks to be the most mature so having a canonical implementation of both 6902 and 7396 would be great.

```
[
  {"op": "replace", "path": "/name", "value": "Jane"},
  {"op": "remove", "path": "/height"}
]
```

**Comment by clagraff** [comment]
Hi @seddonm1 

Would you by chance have an example of _how_ you'd like to interact with `jsonpatch` in creating RFC6902 patches?

**Comment by seddonm1** [comment]
Hi,
i was thinking that you would have a `CreateMergePatch` method for RFC7396 (existing) and a `CreatePatch` method for creating RFC6902 patches?

**Comment by slok** [comment]
Hi!

It this planned to be implemented in a near future?

For example, at this moment some parts of Kubernetes apiserver like the admission webhooks only [allow](https://github.com/kubernetes/api/blob/8be2a0b24ed0dac9cfc1ac2d987ea16cfcdbecb6/admission/v1beta1/types.go#L90) `RFC6902` patches, that's why this feature would be interesting.

Thank you!

**Comment by clagraff** [comment]
Hi @slok ,
Thanks for the bump.

Any thoughts @evanphx ?

Honestly, it slipped under my radar and I've forgotten about this. 😞 Oops.

I will take a look this week, and see what it'd take to do this. Unless someone else wants to tackle this, I'll see what I can do.

**Comment by evanphx** [comment]
This is not planned but I'm happy to review a PR on it!

**Comment by herkyl** [comment]
I'm happy to provide a monetary bounty to anyone interested in building this.

**Comment by herkyl** [comment]
For the people who stumble upon this issue, I wrote a [Go library for creating RFC6902 Patch Documents](https://github.com/herkyl/patchwerk).

You can create patches using Patchwerk and apply them using evanphx/json-patch.
