### ISSUE TITLE
Test Entire Document

### ISSUE THREAD

**Issue by njhugs** [evanphx/json-patch#67]
Does this library support testing an entire JSON document by specifying a root "/" path? I see that it works for replace. If we can't currently test against root "/", is that something folks would be interested in me opening a PR for?

**Comment by evanphx** [comment]
Can you give me an example?

**Comment by njhugs** [comment]
@evanphx absolutely. If I have this JSON document that I want to test against:

`{"field1": 1, "field2": "2"}`

And I do something like this:

`{
    "patch": [
        {"op": "test", "path": "/, "value": {"field1": 1, "field2": "2"}}
    ]
}`

Should that be a successful test?

**Comment by evanphx** [comment]
Sure, you can patch / just like an other object.
