### ISSUE TITLE
move op for array, the result is not correct

### ISSUE THREAD

**Issue by own-idea** [evanphx/json-patch#69]
hello，move op should do same thing with remove op and add op, but i found the result is incorrect in some case. original document array has four elements, but after move op, only three elements if from index is the last index. demo is here, please check it, thanks 
```
package main

import (
	"fmt"
	jsonpatch "github.com/evanphx/json-patch"

)

func main() {
	original := []byte(`{"env":[{"name": "weight","value":"121"},{"name": "height","value":"160"},{"name": "age"},{"name": "job","value":"teacher"}]}`)
	patchJSON := []byte(`[
                 {"op": "move", "from":"/env/3","path": "/env/1"}
	]`)

	patch, err := jsonpatch.DecodePatch(patchJSON)
	if err != nil {
		panic(err)
	}

	modified, err := patch.Apply(original)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Original document: %s\n", original)
	fmt.Printf("Modified document: %s\n", modified)
}
```

**Comment by DoubleFaults** [comment]
hi, imho, this behavior is good to me, it just likes `mv` command in Shell

for your situation, it might be

```json
[
  {"op": "copy", "from":"/env/1","path": "/env/4"},
  {"op": "move", "from":"/env/3","path": "/env/1"}
])
```
hope this helps

**Comment by own-idea** [comment]
> hi, imho, this behavior is good. It just likes `mv` command in Shell
> 
> for your situation, it might be
> 
> ```json
> [
>   {"op": "copy", "from":"/env/1","path": "/env/4"},
>   {"op": "move", "from":"/env/3","path": "/env/1"}
> ])
> ```
> 
> hope this helps

but the move op should be a remove op and add op, so the result should be four elements, right? if move from /env1 to /env/3, then the result is four elements.

**Comment by DoubleFaults** [comment]
> > hi, imho, this behavior is good. It just likes `mv` command in Shell
> > for your situation, it might be
> > ```json
> > [
> >   {"op": "copy", "from":"/env/1","path": "/env/4"},
> >   {"op": "move", "from":"/env/3","path": "/env/1"}
> > ])
> > ```
> > 
> > 
> > hope this helps
> 
> but the move op should be a remove op and add op, so the result should be four elements, right? if move from /env1 to /env/3, then the result is four elements.

Yes, You're right.

I read the codes and found there may be a mistake:

[patch.go#L367~L373](https://github.com/evanphx/json-patch/blob/master/patch.go#L367~L373)

I think it should be

```go
// always, sz := len(cur) + 1
copy(ary, cur[:idx])
if idx >= len(ary) {
	return fmt.Errorf("Unable to access invalid index: %d", idx)
}
ary[idx] = val
ary = append(ary[:idx+1], cur[idx:]...)
```

**Comment by evanphx** [comment]
There is a test case for this that passes fine, namely moving an entry in an array to a different position. Could you retest with the latest release?

**Comment by lucab** [comment]
If I'm reading this correctly, https://github.com/evanphx/json-patch/pull/73 (part of 4.2.0) should have fixed exactly this.

**Comment by own-idea** [comment]
> There is a test case for this that passes fine, namely moving an entry in an array to a different position. Could you retest with the latest release?

test passed in v4.2.0  @evanphx thanks
