### ISSUE TITLE
Please create a newer release that includes #74

### ISSUE THREAD

**Issue by fejta** [evanphx/json-patch#76]
Kubernetes now depends on https://github.com/evanphx/json-patch/pull/74 however the latest tagged release, 4.1.0 does not yet have this commit. 

The go module system will not choose a commit after the latest tagged release, requiring a replace stanza.

This will cause modules using github.com/evanphx/json-patch and k8s.io/apiserver to require a replace stanza

/cc @caesarxuchao @evanphx 

```console
# k8s.io/apiserver/pkg/server
../../../go/pkg/mod/k8s.io/apiserver@v0.0.0-20190406052822-6b396918ed3b/pkg/server/config.go:484:33: undefined: jsonpatch.AccumulatedCopySizeLimit
../../../go/pkg/mod/k8s.io/apiserver@v0.0.0-20190406052822-6b396918ed3b/pkg/server/config.go:488:34: undefined: jsonpatch.AccumulatedCopySizeLimit
FAILED
```

ref https://github.com/kubernetes/test-infra/issues/12107

**Comment by evanphx** [comment]
Sorry about that! Pushed a release just now.

**Comment by fejta** [comment]
Thanks so much! 😻
