### ISSUE TITLE
generate operations patch

### ISSUE THREAD

**Issue by benitogf** [evanphx/json-patch#77]
would be nice to be able to generate patches as per https://tools.ietf.org/html/rfc6902 

some ideas on it here:  https://github.com/mattbaird/jsonpatch/issues/19

Thanks 🏭

**Comment by evanphx** [comment]
Generating operations patches are outside the scope of this package.

**Comment by herkyl** [comment]
@evanphx should patch generation go into a new project then? Or would you still be interested in a PR?
The way I see it (as an end user) it does make sense for this project to also generate these patches, as it can already consume them.

**Comment by marcelometal** [comment]
hi @evanphx,

sorry to bother you, but why generating operations patches are outside the scope of this package?

**Comment by evanphx** [comment]
@marcelometal Because I don't want to enlarge the surface area of this package any more.

**Comment by herkyl** [comment]
I'm still using evanphx/json-patch but wrote my own library to generate the patches, check it out: https://github.com/herkyl/patchwerk
