### ISSUE TITLE
according to RFC6902 JSON patch, replace operation should fail if path not exist before 

### ISSUE THREAD

**Issue by jerreli** [evanphx/json-patch#78]
This issue is the same as the previous issues(#18 and #40). 
According to RFC6902 JSON patch, replace operation should fail if path not exist before. From issue#40, the auther may have merged updated code. But now when I compare codes in branch master or tag 4.2.0, I find that the place that should be updated is not updated. Does the author have other concerns? Expect the author to update the code as soon as possible~~

code in branch master and tag 4.2.0 in method replace:
```go	
_, ok := con.get(key)
if ok != nil {
	return fmt.Errorf("jsonpatch replace operation does not apply: doc is missing key: %s", path)
}
```

code may be merged in method replace:
```go	
val, ok := con.get(key)
if val == nil || ok != nil {
	return fmt.Errorf("jsonpatch replace operation does not apply: doc is missing key: %s", path)
}
```

**Comment by evanphx** [comment]
That code doesn't work, it will fail things that should pass today. Can you provide an example of a patch that doesn't work right?

**Comment by Loushu** [comment]
`package main

import (
	"fmt"
	"github.com/evanphx/json-patch"
)

func main() {
	original := []byte(`{ "Metadata": {	} }`)
	patchJSON := []byte(`[
		{"op": "replace", "path": "/Metadata/key1", "value": "val1"}
	]`)

	patch, err := jsonpatch.DecodePatch(patchJSON)
	if err != nil {
		panic(err)
	}

	modified, err := patch.Apply(original)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Original document: %s\n", original)
	fmt.Printf("Modified document: %s\n", modified)
}`

Expected result: failure to apply patch/panic
Actual result:
Original document: { "Metadata": {	} }
Modified document: {"Metadata":{"key1":"val1"}}

**Comment by evanphx** [comment]
Closed as stale.
