### ISSUE TITLE
extend patch to be able to filter arrays on values

### ISSUE THREAD

**Issue by utako** [evanphx/json-patch#80]
Do you have any interest in extending json-patch to be able to filter on values? e.g. if you have the original json:

```
{
 "baz": [
    { "bar": "foo"},
    { "bar": "qux"}
  ]
}
```
and the patch:
```
 { "op": "replace", "path": "/baz/bar=foo/bar", "value": "baz" } ]
```
with the patch applied, the json would be:
```
{
 "baz": [
    { "bar": "baz"},
    { "bar": "qux"}
  ]
}
```

**Comment by evanphx** [comment]
If it's not in the RFC, then it shouldn't be in this package. Two reasons: 1) I'm trying to limit the scope of this package and have it be "finished". 2) adding that kind will be very unexpected by lots of users so will require conditions to activate, etc. That tells me it's best for another package.
