### ISSUE TITLE
Support use of different JSON library

### ISSUE THREAD

**Issue by zachelrath** [evanphx/json-patch#82]
We heavily use https://godoc.org/github.com/json-iterator/go as an alternative to the standard `encoding/json` library, because of capabilities it provides that the standard library does not (e.g. sorting of map keys), as well as performance. We would like to be able to configure `json-patch` to use a different JSON library for `Marshal()` and `Unmarshal()` calls.

If `json-patch` defined a public interface that supported all of the functions on the standard `encoding/json` library, and supported the ability to configure the json library to use, then this would enable us to use `json-patch` but have `json-patch` delegate the marshal / unmarshal / indent / etc. calls to our desired JSON library.

**Comment by evanphx** [comment]
Closing as I've opt'd to close #83 as well.
