### ISSUE TITLE
Is there a good way to specify only a subset of operations is enabled?

### ISSUE THREAD

**Issue by yanfali** [evanphx/json-patch#9]
Is anyone working on a way to specify which operations were supported by which fields of a document. Would that violate the RFC? mholt/binding has this concept of a FieldMap where different options can be specified per field in a data structure.

Would there be any interest in adding something similar to json-patch?

e.g.

type User struct {
    Name string
    Hobbies []string
}

func (u *User) FieldMap() FieldMap {
  return FieldMap {
    &u.Name: Field{
      Operations: [ Replace ],
    },
    &u.Hobbies: Field{
      Operations: [ Replace, Add, Remove ]
    },
  }
}

**Comment by evanphx** [comment]
The RFC doesn't cover that, it treats all fields the same, in terms of their type determining the operations only.
