### ISSUE TITLE
add op for a patch does not work as expected for adding new member

### ISSUE THREAD

**Issue by xunpan** [evanphx/json-patch#92]
According to https://tools.ietf.org/html/rfc6902#page-12:
```
   An example target JSON document:
   { "foo": "bar"}
   A JSON Patch document:
   [
     { "op": "add", "path": "/baz", "value": "qux" }
   ]
   The resulting JSON document:
   {
     "baz": "qux",
     "foo": "bar"
   }
```
It shows if there is no key `baz`, it will be created for `add` op.

However, it seems not work with `json-patch`. I'm working on `kubefed` project, I use below patch
```
     - path: "/metadata/annotations/foo"
       op: "add"
       value: "bar"
```
The `add` result shows `add operation does not apply: doc is missing path: "/metadata/annotations/foo": missing value`

I checked code https://github.com/evanphx/json-patch/blob/e83c0a1c26c884f8ec4fb743f6db92a941f605f1/patch.go#L504

It seems before `add`, the code needs to get it first. I guess this is a bug. For `add` op, we should try the prefix if the whole path cannot be find.

Any comments?
@evanphx

**Comment by evanphx** [comment]
According to the RFC section A.12, we're doing the correct thing as you're attempting to add to a nonexistent object in annotations.

You have to add each part of the path first.
